# Generated by Django 5.2.1 on 2025-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
