# Generated by Django 5.2.1 on 2025-05-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
