# Generated by Django 5.2.1 on 2025-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='profile_photos'),
        ),
        migrations.AddField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
